### ISSUE TITLE
Cannot run CiteRank: Issue with parsing?

### ISSUE THREAD

**Issue by Manajit89** [diwis/PaperRanking#2]
Hi! I am trying to run CiteRank on a file containing input in the format specified but I run into a strange error:
 
![screen shot 2018-07-03 at 1 53 15 pm](https://user-images.githubusercontent.com/33542824/42218680-b292f678-7ec9-11e8-92ee-61d6709724b0.png)

I am using the following command for running the program:
`python citerank.py input_citerank.txt 0.5 2.6 2008 0.0001 100`

I am wondering if this is an issue with the input file or the code itself. I could not single out the source of the error after frantically going through the code numerous times.

For reference, I am attaching a sample of my input file below:
[sampleinput_citerank.txt](https://github.com/diwis/PaperRanking/files/2159173/sampleinput_citerank.txt)

Thanking you in anticipation.

Bests,
Manajit

**Comment by diwis** [comment]
Dear @Manajit89 
First of all, thank you very much for your interest in our library. 
The problem seems to be related with the input file and especially with the papers that do not reference other papers. These rows should have the following form: 
`<paper id>\t0|0|<current paper score>\t<previous paper score>\t<publication year>`
an example is `0579355	0|0|0.0000015574	0	1998`
Note that for the rest of the papers that have a non-empty list of referenced papers, each referenced paper id should also correspond to row with the paper id as a first field.
We also have updated the related [section](https://github.com/diwis/PaperRanking#paper-data-input-files) of the readme file to clarify this issue.
Please feel free to contact us in case of any further issues.

**Comment by Manajit89** [comment]
Dear @diwis 
Thank you so much. I kind of had the feeling it had to do with the papers not having citations. I corrected my input file accordingly. So, all my citing and cited papers are in the format that you specified, but I am still unable to resolve the issue. It is throwing me the same errors nonetheless. I am attaching the complete input file, just for reference.
[input_citerank.txt](https://github.com/diwis/PaperRanking/files/2163733/input_citerank.txt)

Thank you once again for your prompt support.

**Comment by Manajit89** [comment]
Hi again,

It is quite surprising that with the same command and the same path, I am unable to run the program. I am encountering the following error now:
![screen shot 2018-07-06 at 12 33 56 pm](https://user-images.githubusercontent.com/33542824/42374662-20f89d1a-8119-11e8-8794-7e14401c82f5.png)

Unlike last time, where it was throwing me the error the moment I ran the code, here it seems to take a bit of time before exiting with errors. FYI, I am running Python 2.7.13 on macOS High Sierra 10.13.5. I am inclined to believe that it is not a versioning issue?

Thank you for the continuing support.

**Comment by Manajit89** [comment]
Hi @diwis ,
It seems I had inadvertently made some changes to the code of citerank_reduce.py, which is why it was throwing me such errors. It seems to be fixed now. Thanks a lot for all the support and especially for your amazing library! :)
